name: Deploy Service

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      CLUSTER_NAME:
        required: true
        type: string
      REGION:
        required: true
        type: string
      ADDITIONAL_ENVIRONMENT_VARS:
        required: false
        type: string
    secrets:
      ROLE_TO_ASSUME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.REGION }}

      - name: Get task definition
        env:
          CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
          APP_NAME: ${{ inputs.APP_NAME }}
        run: |
          TASK_DEFINITION="$CLUSTER_NAME-$APP_NAME-task"
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query taskDefinition > $APP_NAME-task-definition.json
          echo $(cat $APP_NAME-task-definition.json | jq 'del(
                  .taskDefinitionArn,
                  .requiresAttributes,
                  .compatibilities,
                  .revision,
                  .status,
                  .registeredAt,
                  .registeredBy
              )') > $APP_NAME-task-definition.json

      - name: Update task definition
        id: update-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ inputs.APP_NAME }}-task-definition.json
          container-name: ${{ inputs.APP_NAME }}
          image: ${{ inputs.IMAGE }}
          environment-variables: ${{ inputs.ADDITIONAL_ENVIRONMENT_VARS }}

      - name: Deploy to cluster
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.update-task.outputs.task-definition }}
          service: ${{ inputs.APP_NAME }}
          cluster: ${{ inputs.CLUSTER_NAME }}
          wait-for-service-stability: true
